language: bash

services: docker

env:
  - TAG=latest  PHP=7.2 V_AST=1.0.0 V_PROTO=3.6.1 V_SWOOLE=1.10.5
  - TAG=7.2-sw4 PHP=7.2 V_AST=1.0.0 V_PROTO=3.6.1 V_SWOOLE=4.2.11
  - TAG=7.3-sw4 PHP=7.3 V_AST=1.0.0 V_PROTO=3.6.1 V_SWOOLE=4.2.11

script:
  - docker pull carno/php:$TAG || true
  - |
    (
      set -x
      docker build -t carno/php:$TAG \
        --build-arg PHP_BASE=php:$PHP-cli-alpine \
        --build-arg AST_VER=$V_AST \
        --build-arg PROTO_VER=$V_PROTO \
        --build-arg SWOOLE_VER=$V_SWOOLE \
      runtime
    )
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push carno/php:$TAG
